vehicle_prompt = """The vehicle in the images is a Vehicle. Fetch me information about 'type', 'hasOversizedCargo', isBehindPhysicalBarrier', 'isBrakeLightsOn', 'isCargo', 'isDoorOpen',
'isDummy','isFlashingLightsOn','isIgnoreArea','isReverseLightsOn','isTurnLightIndicatorLeftOn','isTurnLightIndicatorRightOn','isVehicleLightsOn','isWarnLightsOn','occlusion','truncation' these attributes.
The type of vehicle is 'PassengerCar' if it is a car, jeeps, SUVs, pickups, and vans with continuous body shape.
The type of vehicle is set to 'Truck' if it is a large vehicle designed to transport cargo, carry speacial equipment, or perform other utilitarian tasks.
The type of vehicle is 'Bus' if it is a large vehicle with a great amount of seats usually seen as a public transportation.
The type of vehicle is 'CarTrailer' if it is a vehicle designed to be towed by a car or truck.
The type of vehicle is 'Excavator' which is a large, construction vehicle designed for digging out earth with its bucket to create trenches, holes and foundations.
The type is set to 'Train' which refers to a form of rail transport consisting of a series of connected wagons that typically run along a rail track to transport either cargo or passengers.
The type is set to 'TruckTrailer,' which refers to an unpowered, multi-wheeled trailer pulled by a truck to transport goods and materials. Its size is typically enclosed, matching or exceeding the height of the truck that pulls it. In its open form, goods or materials may be visible during transportation.
The type is set to 'FunVehicle' which refers to a vehicle designed for recreational use.
The type is set to 'AgriculturalVehicle,' which describes motorized vehicles, typically equipped with large, heavily treaded rear tires, and are primarily used as farm machinery, such as pulling farm implements.
The type is set to 'Forklift' which is a powered special vehicle used to lift and move materials over short distances in construction areas or industrial fields.
Identify 'type' of vehicle from ['PassengerCar', 'Truck', 'Bus', 'CarTrailer', 'Excavator', 'Train', 'TruckTrailer','FunVehicle', 'AgriculturalVehicle','Forklift']. If the cargo is horizontally extended from the vehicle the set the 'hasOversizedCargo' to True else if it is attached vertically or if there is no cargo attached to the vehicle then set it to False.
If the Physical barrier is continuous and is at least as high as the wheel of the vehicle the set 'isBehindPhysicalBarrier' to True else False.If brake lights on rear side of this vehicle are glowing the set the 'isBrakeLightsOn' to True,
else False.If The vehicle is on top of another vehicle set 'isCargo' to True else False.If The door(s) or trunk lid of the vehicle is open then set 'isDoorOpen' to True, else if all the doors and trunk lid is closed then set to False.
If Vehicle is present as a dummy then set'isDummy' to True else False.If Duty lights of emergency or non-duty vehicle are on then set 'isFlashingLightsOn' to True else False.If the vehicle in the image appears in any of the following
scenarios: Reflection or depiction on billboard or Behind glass in an enclosed space or Behind physical separation then set 'isIgnoreArea' to True else False.If the Reverse lights on rear side of this vehicle are glowing then set
'isReverseLightsOn' to True else False.If Vehicle has its turn light indicator directing to the left on then set 'isTurnLightIndicatorLeftOn' to On else Off.If Vehicle has its turn light indicator directing to the right on then
set 'isTurnLightIndicatorRightOn' to On else Off.If At least one of the vehicle main lights (on front or rear side of the vehicle) is on then set 'isVehicleLightsOn' to True else False.
If All turn light indicators of this vehicle (on front or rear side of the vehicle) are Flashing at the same time then set 'isWarnLightsOn' to True else False. occlusion is anything that covers parts of a vehicle. a
occlusion is anything that is located between the vehicle and the camera (transparent objects are included). It is set to 0.0 if the object is fully visible. It is set to 20.0 if 1-20percent of object is occluded. It is set to 40.0 if 21-40percent of object is occluded.
It is set to 60.0 if 41-60percent of object is occluded. It is set to 80.0 if 61-80percent of object is occluded. It is set to 99.0 if 81-99percent of object is occluded.Truncated objects are objects that are partly outside of the image.
It is set to 0.0 if truncated objects are objects that are partly outside of the image. It is set to 20.0 if 1-20percent object is truncated, i.e. not in field-of-view. It is set to 40.0 if 21-40percent object is truncated, i.e. not in field-of-view.
It is set to 60.0 if 41-60percent object is truncated, i.e. not in field-of-view. It is set to 80.0 if 61-80percent object is truncated, i.e. not in field-of-view. It is set to 99.0 if 81-99percent object is truncated, i.e. not in field-of-view.
Generate only JSON in the following format: {{\"Vehicle\": {{\"type\": \"{{value16}}\", {{\"hasOversizedCargo\": \"{{value1}}\", \"isBehindPhysicalBarrier\": \"{{value2}}\", \"isBrakeLightsOn\": \"{{value3}}\", \"isCargo\": \"{{value4}}\",
\"isDoorOpen\": \"{{value5}}\", \"isDummy\": \"{{value6}}\", \"isFlashingLightsOn\": \"{{value7}}\", \"isIgnoreArea\": \"{{value8}}\", \"isReverseLightsOn\": \"{{value9}}\", \"isTurnLightIndicatorLeftOn\": \"{{value10}}\",
\"isTurnLightIndicatorRightOn\": \"{{value11}}\", \"isVehicleLightsOn\": \"{{value12}}\", \"isWarnLightsOn\": \"{{value13}}\", \"occlusion\": \"{{value14}}\", \"truncation\": \"{{value15}}\"}}}} Here {{value16}} will be replaced by type value, {{value1}} will be replaced by hasOversizedCargo value, {{value2}} will be replaced by isBehindPhysicalBarrier value, {{value3}} will be replaced by isBrakeLightsOn value, {{value4}} will be replaced by isCargo value, {{value5}} is replaced by isDoorOpen value, {{value6}} will be replaced by isDummy value, {{value7}} will be replaced by isFlashingLightsOn value,{{value8}} will be replaced by isIgnoreArea value,{{value9}} will be replaced by isReverseLightsOn value,
{{value10}} will be replaced by isTurnLightIndicatorLeftOn value,{{value11}} will be replaced by isTurnLightIndicatorRightOn value,{{value13}} will be replaced by isWarnLightsOn value,{{value14}} will be replaced by occlusion value and {{value15}} will be replaced by truncation value.
Ensure that the output generated belongs to the list of possible values."""